### ISSUE TITLE
Doesn't seem to work with GHC 9.4.1

### ISSUE THREAD

**Issue by yav** [GaloisInc/parameterized-utils#141]
I get the following error:
```
src/Data/Parameterized/Classes.hs:354:10: error:
    • Could not deduce (TestEquality f)
        arising from the superclasses of an instance declaration
      from the context: HashableF f
        bound by the instance declaration
        at src/Data/Parameterized/Classes.hs:354:10-46
      Possible fix:
        add (TestEquality f) to the context of the instance declaration
    • In the instance declaration for ‘Hashable (TypeAp f tp)’
    |
354 | instance HashableF f => Hashable (TypeAp f tp) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
I don't think this is an issue with GHC 9.4.1 so much as it is an issue with `hashable-1.4.*`—see #126. I have a fix for this in #127 that is awaiting review.

I do expect there to be other changes needed for GHC 9.4, however—we should try again after landing a fix for #126.

**Comment by RyanGlScott** [comment]
After landing #127, the only other change that needs to be made (AFAICT) is enabling `UndecidableInstances` in a place that didn't require it before:

```diff
diff --git a/src/Data/Parameterized/Fin.hs b/src/Data/Parameterized/Fin.hs
index 46caafb..eaa48ce 100644
--- a/src/Data/Parameterized/Fin.hs
+++ b/src/Data/Parameterized/Fin.hs
@@ -6,6 +6,7 @@
 {-# LANGUAGE ScopedTypeVariables #-}
 {-# LANGUAGE TypeApplications #-}
 {-# LANGUAGE TypeOperators #-}
+{-# LANGUAGE UndecidableInstances #-}
 
 {-|
 Copyright        : (c) Galois, Inc 2021
```
